MiniProject/src/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

MiniProject/src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Country</label>
</CustomObject>

MiniProject/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Applying_for__c</fullName>
        <label>Course Applying for</label>
        <picklist>
            <picklistValues>
                <fullName>B.Arch.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.C.A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.C.A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>H_S_C__c</fullName>
        <label>H.S.C %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Roll_number__c</fullName>
        <label>Roll number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_S_C__c</fullName>
        <label>S.S.C %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MiniProject/src/classes/TestStudentRegistrationPage.cls
@isTest
public with sharing class TestStudentRegistrationPage {

	static testmethod void testStudent(){
		
		Student__c st=new Student__c();
		st.Student_Name__c='nikhil Chavan';
		st.Roll_number__c=123;
		st.Gender__c='Male';
		st.Course_Applying_for__c='B.E';
		st.H_S_C__c=80;
		st.S_S_C__c=90;
		st.Country__c='India';
		st.State__c='Maharashtra';
		st.City__c='nashik';
		
		
		
		Pagereference pageref = Page.StudentRegistrationForm;
		test.setCurrentPage(pageref);
		Apexpages.Standardcontroller ac = new Apexpages.Standardcontroller(st);
		
		StudentDetails obj = new StudentDetails(ac);
		obj.submit();
		
		Student__c st1=new Student__c();
		st.Student_Name__c=null;
		st.Roll_number__c=0;
		st.Gender__c=null;
		st.Course_Applying_for__c=null;
		st.H_S_C__c=80;
		st.S_S_C__c=90;
		st.Country__c=null;
		st.State__c=null;
		st.City__c=null;
		
		
		Apexpages.Standardcontroller ac1 = new Apexpages.Standardcontroller(st1);
		
		StudentDetails obj1 = new StudentDetails(ac1);
		obj1.submit();
		
		obj.selectedLang = 'French';
		
		obj.changeLanguage();
		
		User usr = [SELECT Id, LanguageLocaleKey FROM User WHERE Id=:UserInfo.getUserId()];
		System.assertEquals('fr', usr.LanguageLocaleKey);
		
		obj.selectedLang = 'Spanish';
		
		obj.changeLanguage();
		
		usr = [SELECT Id, LanguageLocaleKey FROM User WHERE Id=:UserInfo.getUserId()];
		System.assertEquals('es', usr.LanguageLocaleKey);
		
		obj.selectedLang = 'English';
		
		obj.changeLanguage();
		
		usr = [SELECT Id, LanguageLocaleKey FROM User WHERE Id=:UserInfo.getUserId()];
		System.assertEquals('en_US', usr.LanguageLocaleKey);
		
	}
	
}